#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: apt NOTIFICATION_SERVICE"
    exit 1
fi

apt update > /tmp/an-apt.log 2> /dev/null
apt_result=$(tail -n 1 /tmp/an-apt.log)

if [ x"${apt_result}" = x"All packages are up to date." ]; then
    /usr/local/bin/admin-notifier $1 System debian $(hostname) PackagesObsoleteOK "${apt_result}" 7
else
    packages_count=$(echo $apt_result | cut -d' ' -f1)
    message="${packages_count} package"
    [ ${packages_count} -ne 1 ] && message="${message}s"
    /usr/local/bin/admin-notifier $1 System debian $(hostname) PackagesObsolete   "${message} upgradable" 7
fi
