#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: diskspace NOTIFICATION_SERVICE"
    exit 1
fi

FAILED80=""
FAILED90=""
df -lhT -x tmpfs -x devtmpfs | grep -v "^Filesystem" \
    | awk '{print $7 " at " $6 " (" $1 ")"}' | uniq -f 2 \
    | while read line; do
          line_array=(${line})
          if [ ${line_array[3]} = "(overlay)" ]; then continue; fi
          if [ ${line_array[2]:0: -1} -lt 80 ]; then
              FAILED80="${FAILED80}${line_array[0]} "
          elif [ ${line_array[2]:0: -1} -lt 90 ]; then
              FAILED90="${FAILED90}${line_array[0]} "
          fi
done
if [ -z ${FAILED80} ] && [ -z ${FAILED90} ]; then
    /usr/local/bin/admin-notifier $1 System os $(hostname) DiskspaceCriticalOK "All disks below 80%" 0
elif [ -z ${FAILED90} ]; then
    /usr/local/bin/admin-notifier $1 System os $(hostname) DiskspaceCritical   "Disks above 80%: ${FAILED80}" 0
elif [ -z ${FAILED80} ]; then
    /usr/local/bin/admin-notifier $1 System os $(hostname) DiskspaceCritical   "Disks above 90%: ${FAILED90}" 0
else
    /usr/local/bin/admin-notifier $1 System os $(hostname) DiskspaceCritical   "Disks above 90%: ${FAILED90}, Disks above 80%: ${FAILED80}" 0
fi
