#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: diskspace NOTIFICATION_SERVICE"
    exit 1
fi

title="$(hostname): diskspace critical"
df -lhT -x tmpfs -x devtmpfs | grep -v "^Filesystem" \
    | awk '{print $7 " at " $6 " (" $1 ")"}' | uniq -f 2 \
    | while read line; do
          line_array=(${line})
          if [ ${line_array[3]} = "(overlay)" ]; then continue; fi
          if [ ${line_array[2]:0: -1} -lt 80 ]; then
              /usr/local/bin/admin-notifier $1 System DiskspaceCriticalOK "$(hostname):${line_array[0]}" os "${line}"
          else
              /usr/local/bin/admin-notifier $1 System DiskspaceCritical   "$(hostname):${line_array[0]}" os "${line}"
          fi
      done
