#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: kernel NOTIFICATION_SERVICE"
    exit 1
fi

loaded_kernel=$(uname -r)
last_kernel=$(ls -tr /boot/vmlinuz-* | tail -n1 | sed 's|/boot/vmlinuz-||')

if [ x${loaded_kernel} = x${last_kernel} ]; then
    /usr/local/bin/admin-notifier $1 NewKernelAvailableOK $(hostname) system "Last kernel running"
else
    message="Loaded kernel is ${loaded_kernel}, ${last_kernel} is installed, reboot asap"
    /usr/local/bin/admin-notifier $1 NewKernelAvailable   $(hostname) system "${message}"
fi
