#! /bin/bash

load=$(cut -d' ' -f3 /proc/loadavg)
load_int=$(echo ${load} | sed 's/\..*//')
processors=$(grep "^processor" /proc/cpuinfo | wc -l)

if [ ${load_int} -lt $((2 * ${processors})) ]; then
    /usr/local/bin/alerta-notify System os $(hostname) LoadCriticalOK "Load: ${load}" 5
else
    /usr/local/bin/alerta-notify System os $(hostname) LoadCritical   "Load: ${load}" 5
fi
