#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: mdadm NOTIFICATION_SERVICE"
    exit 1
fi

[ -b /dev/md/0 ] || exit 0

for i in /dev/md/*; do
    mdadm --detail $i > /tmp/an-mdadm.log
    grep -q "State : clean" /tmp/an-mdadm.log || \
        grep -q "State : active" /tmp/an-mdadm.log || \
        /usr/local/bin/admin-notifier $1 MdadmError $(hostname) mdadm "Array $i not clean, check mdadm --detail $i"
done
