#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: mdadm NOTIFICATION_SERVICE"
    exit 1
fi

[ -b /dev/md/0 ] || exit 0

for i in /dev/md/*; do
    mdadm --detail $i > /tmp/an-mdadm.log
    if grep -q "State : clean" /tmp/an-mdadm.log || grep -q "State : active" /tmp/an-mdadm.log; then
        /usr/local/bin/admin-notifier $1 Hardware MdadmErrorOK "$(hostname):$(basename $i)" raid "Array clean"
    else
        /usr/local/bin/admin-notifier $1 Hardware MdadmError   "$(hostname):$(basename $i)" raid "Array not clean"
    fi
done
