#! /bin/bash

[ -e /usr/sbin/megacli ] || exit 0

PD_FAILED=""
# Check physical disk state
megacli -PDList -aALL -NoLog | awk '
/Enclosure Device ID:/ {
  device_id = substr($0, 22)
}
/Slot Number:/ {
  slot_number = substr($0, 14)
}
/Firmware state:/ {
  firmware_state = substr($0, 17)
  if (firmware_state != "Online, Spun Up") {
    print "[" device_id ":" slot_number "] KO"
  }
  else {
    print "[" device_id ":" slot_number "] OK"
  }
}
' | while read line ; do
    line_array=($line)
    if [ ${line_array[1]} != OK ]; then
        PD_FAILED="${PD_FAILED}${line_array[0]} "
    fi
done
if [ -z ${PD_FAILED} ]; then
    /usr/local/bin/alerta-notify Hardware raid $(hostname) MegacliPDErrorOK  "All physical disks online" 1
else
    /usr/local/bin/alerta-notify Hardware raid $(hostname) MegacliPDError    "Physical disks falty: ${PD_FAILED}" 1
fi

LD_FAILED=""
# Check virtual disk state
megacli -LDInfo -Lall -aALL -NoLog | awk '
/Virtual Drive:/ {
  device_id = $3
}
/State/ {
  firmware_state = $3
  if (firmware_state != "Optimal") {
    print "[" device_id "] KO"
  }
  else {
    print "[" device_id "] OK"
  }
}
' | while read line; do
    line_array=($line)
    if [ ${line_array[1]} != OK ]; then
        LD_FAILED="${LD_FAILED}${line_array[0]} "
    fi
done
if [ -z ${LD_FAILED} ]; then
    /usr/local/bin/alerta-notify Hardware raid $(hostname) MegacliLDErrorOK  "All logical disks online" 1
else
    /usr/local/bin/alerta-notify Hardware raid $(hostname) MegacliLDError    "Logical disks falty: ${LD_FAILED}" 1
fi
