#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: monitor-snapshots NOTIFICATION_SERVICE"
    exit 1
fi

[ -e /etc/admin-notifier/monitor-snapshots.list ] && SNAPSHOTS=$(cat /etc/admin-notifier/monitor-snapshots.list)

MISSING_SNAPSHOTS=""

for host_volume in ${SNAPSHOTS}; do
    host=$(echo ${host_volume} | cut -d':' -f1)
    volume=$(echo ${host_volume} | cut -d':' -f2)

    if [ -d /srv/snapshots/${host}/${volume}.daily-$(date +%Y-%m-%d) ]; then
        /usr/local/bin/admin-notifier $1 Snapshots MissingSnapshotsOK ${host_volume} snapshots "${host_volume} backed up"
    else
        /usr/local/bin/admin-notifier $1 Snapshots MissingSnapshots   ${host_volume} snapshots "${host_volume} missing"
    fi
done
