#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: systemd NOTIFICATION_SERVICE"
    exit 1
fi

[ -e /etc/admin-notifier/monitor-urls.list ] && CURL_LIST=$(cat /etc/admin-notifier/monitor-urls.list)

curl_test() {
    SERVICE=$2
    URL=$3
    HTTP_RESPONSE=$(curl -s -k "${URL}" --max-time 10 -o /dev/null -w "%{http_code}")
    if [ ${HTTP_RESPONSE} -eq 200 ]; then
        /usr/local/bin/admin-notifier $1 Webserver SiteDownOK ${SERVICE} http "${URL} is up"
    else
        /usr/local/bin/admin-notifier $1 Webserver SiteDown   ${SERVICE} http "${URL} is down"
    fi
}


for TEST in ${CURL_LIST}; do
    SERVICE=$(echo ${TEST} | cut -d';' -f1)
    URL=$(echo ${TEST} | cut -d';' -f2)
    if [ -z "${SERVICE}" ] || [ -z "${URL}" ] ||\
           [ "${SERVICE};${URL}" != "${TEST}" ]; then
        echo "error: Unvalid line: ${TEST}"
        continue
    fi
    {
        curl_test $1 ${SERVICE} ${URL}
    } &
done
wait
