#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: monitor-snapshots NOTIFICATION_SERVICE"
    exit 1
fi

[ -e /etc/admin-notifier/monitor-snapshots.list ] && SNAPSHOTS=$(cat /etc/admin-notifier/monitor-snapshots.list)

for host_volumes in ${SNAPSHOTS}; do
    FAILED=""
    host=$(echo ${host_volumes} | cut -d':' -f1)
    volumes=$(echo ${host_volumes} | cut -d':' -f2-)
    for volume in ${volumes//:/ }; do
        if [ ! -d /srv/snapshots/${host}/${volume}.daily-$(date +%Y-%m-%d) ]; then
            FAILED="${FAILED}${volume}"
        fi
    done
    if [ -z ${FAILED} ]; then
        /usr/local/bin/admin-notifier $1 Snapshots snapshots ${host} MissingSnapshotsOK "All snapshots backed up" 3
    else
        /usr/local/bin/admin-notifier $1 Snapshots snapshots ${host} MissingSnapshots   "Snapshots missing: ${FAILED}" 3
    fi
done
