#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: mysql-dumps NOTIFICATION_SERVICE"
    exit 1
fi

for DB in $(mysql -N -s --execute 'SHOW DATABASES'); do
    if [ "${DB}" = information_schema ] || [ "${DB}" = performance_schema ]; then
        continue
    fi
    if [ $(find /var/lib/mysql-dumps -name ${DB}.sql.gz -mtime -1 | wc -l) -ne 0 ]; then
        /usr/local/bin/admin-notifier $1 Database MysqlMissingDumpOK "$(hostname):${DB}" mysql "${DB} dumped"
    else
        /usr/local/bin/admin-notifier $1 Database MysqlMissingDump   "$(hostname):${DB}" mysql "${DB} dump missing"
    fi
done
