#! /bin/bash

mysql --execute="" 2> /dev/null

if [ $? -eq 0 ]; then
    /usr/local/bin/alerta-notify Database mysql $(hostname) MysqlDownOK "Mysql is up" 3
else
    /usr/local/bin/alerta-notify Database mysql $(hostname) MysqlDown   "Mysql is down" 3
    exit 0
fi
