#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: mysql NOTIFICATION_SERVICE"
    exit 1
fi

mysql --execute="" 2> /dev/null

if [ $? -eq 0 ]; then
    /usr/local/bin/admin-notifier $1 Database MysqlDownOK $(hostname) mysql "Mysql is up"
else
    /usr/local/bin/admin-notifier $1 Database MysqlDown   $(hostname) mysql "Mysql is down"
    exit 0
fi
