#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: mysql NOTIFICATION_SERVICE"
    exit 1
fi

mysql --execute="" 2> /dev/null

if [ $? -eq 0 ]; then
    /usr/local/bin/admin-notifier $1 Database mysql $(hostname) MysqlDownOK "Mysql is up" 3
else
    /usr/local/bin/admin-notifier $1 Database mysql $(hostname) MysqlDown   "Mysql is down" 3
    exit 0
fi
