#! /bin/bash

cd /tmp
sudo -u postgres psql -c ""

if [ $? -eq 0 ]; then
    /usr/local/bin/alerta-notify Database postgresql $(hostname) PGDownOK "Postgresql is up" 3
else
    /usr/local/bin/alerta-notify Database postgresql $(hostname) PGDown   "Postgresql is down" 3
    exit 0
fi
