#! /bin/bash

FAILED=""
cd /tmp
for DB in $(sudo -u postgres psql -t -c 'SELECT datname FROM pg_database'); do
    if [ "${DB}" = template1 ] || [ "${DB}" = template0 ]; then
        continue
    fi
    if [ $(find /var/lib/postgresql/dumps -name ${DB}.sql.gz -mtime -1 | wc -l) -eq 0 ]; then
        FAILED="${FAILED}${DB} "
    fi
done

if [ -z ${FAILED} ]; then
    /usr/local/bin/alerta-notify Database postgresql $(hostname) PGMissingDumpOK "All databases dumped" 1
else
    /usr/local/bin/alerta-notify Database postgresql $(hostname) PGMissingDump   "Missing databases dump: ${FAILED}"
fi
