#! /bin/bash

systemctl --failed --all > /tmp/an-systemd.log

if [ x"$(grep 'loaded units listed.$' /tmp/an-systemd.log)" = x"0 loaded units listed." ]; then
    /usr/local/bin/alerta-notify System os $(hostname) SystemdFailedOK "All services up" 3
else
    unit_failed=$(grep 'loaded units listed' /tmp/an-systemd.log | cut -d' ' -f1)
    message="$(head -n $((${unit_failed} + 1)) /tmp/an-systemd.log | tr '\n' ' ')"
    /usr/local/bin/alerta-notify System os $(hostname) SystemdFailed   "${message}" 3
fi
