#! /bin/bash

FAILED=""
for zone in /sys/class/thermal/thermal_zone*; do
    # No trip point
    if [ ! -e ${zone}/trip_point_0_type ]; then continue; fi
    critical_file=""
    zone_id=${zone: -1}
    # Check if there is a critical temperature for each thermal zone
    for type in ${zone}/trip_point_*_type; do
        if [ $(cat ${type}) = "critical" ]; then critical_file=${type:0:-5}_temp; fi
    done
    if [ -z ${critical_file} ]; then continue; fi
    temp=$(cat ${zone}/temp)
    crit=$(cat ${critical_file})
    # Send alert if temperature is above 3/4 of the critical temperature
    if [ ${temp} -gt $((3 * ${crit} / 4)) ]; then
        FAILED="${FAILED}${zone_id} "
    fi
done

if [ -z ${FAILED} ]; then
    /usr/local/bin/alerta-notify Hardware sensors $(hostname) TemperatureCriticalOK "All temperatures below 3/4 of critical" 3
else
    /usr/local/bin/alerta-notify Hardware sensors $(hostname) TemperatureCritical   "Temperatures above 3/4 of critical, check zones: ${FAILED}" 3
fi
